"""initialize migrations

Revision ID: 3e6c7d895ddb
Revises: 
Create Date: 2022-01-05 16:09:38.259126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6c7d895ddb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rejestracja', schema=None) as batch_op:
        batch_op.drop_column('f_dane')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rejestracja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_dane', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
